// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upaydopbdlggwckaudcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwYXlkb3BiZGxnZ3dja2F1ZGNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjE5MzAsImV4cCI6MjA3MTY5NzkzMH0.66VR9uf7Uw1Sf-5wjSiUbgyav75q1AxOHiQ6hRG-5cQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});